name:                haskell-template

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-template-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-template

tests:
  haskell-template-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-template
